In [88]:
import numpy as np
import scipy.stats.stats as st
from astropy.stats import jackknife_resampling
from astropy.stats import jackknife_stats
import matplotlib.pyplot as plt
import plotly.plotly as py
from scipy.stats import norm
from scipy.stats import lognorm

In [76]:
n = 100

In [77]:
data = np.random.random(n)
print data

[ 0.19674408  0.5265011   0.10872798  0.30253675  0.0680024   0.66012012
  0.13581098  0.44438482  0.8652004   0.41821629  0.20230251  0.28087654
  0.91559574  0.21544415  0.32987448  0.73884325  0.52082177  0.06974487
  0.32577455  0.03338356  0.75821065  0.53354322  0.06639091  0.14288146
  0.69088479  0.6818912   0.10688051  0.05767983  0.88711746  0.16070533
  0.11920241  0.42261599  0.03814796  0.42796316  0.4025807   0.98878496
  0.79834213  0.90432255  0.50366493  0.97567006  0.80901577  0.02628437
  0.83102933  0.63985186  0.66194111  0.04532149  0.43868256  0.23722229
  0.02111533  0.61984461  0.54170708  0.54001974  0.5513217   0.17645073
  0.8994159   0.06264102  0.03927723  0.91812488  0.99842306  0.0952035
  0.83059092  0.78022016  0.26494083  0.8957572   0.47259696  0.23632427
  0.81101014  0.37422659  0.50070364  0.29871432  0.31991597  0.40693726
  0.75340734  0.51382668  0.23307102  0.0027264   0.48874002  0.32319061
  0.96435069  0.92138156  0.88916292  0.22918086  0.

In [78]:
plt.hist(data)

(array([ 14.,  10.,  11.,   6.,  10.,  12.,  11.,   5.,  10.,  11.]),
 array([ 0.0027264 ,  0.10229607,  0.20186573,  0.3014354 ,  0.40100507,
         0.50057473,  0.6001444 ,  0.69971406,  0.79928373,  0.8988534 ,
         0.99842306]),
 <a list of 10 Patch objects>)

In [79]:
meann = np.mean(data)
print meann

0.47676024637


In [80]:
sa = st.skew(data)
print sa

0.103587876677


In [94]:
norm_data = st.norm(data)
mean, var, skew, kurt = norm.stats(moments='mvsk')
median = norm.ppf([0.001, 0.5, 0.999])

AttributeError: 'module' object has no attribute 'norm'

In [85]:
log_norm = st.lognorm(1,0)
mean, var, skew, kurt = lognorm.stats(moments='mvsk')
median = log_norm.ppf(0,5)
lognorm_data = log_norm.rvs(n)
plt.hist(lognorm_data,bins=15)

AttributeError: 'module' object has no attribute 'lognorm'

In [64]:
me = np.median(data)
print me

0.479093392659


In [7]:
resamples = jackknife_resampling(data)
resamples

array([[ 0.44920006,  0.37271716,  0.61447907, ...,  0.12700564,
         0.21728054,  0.52173803],
       [ 0.32583649,  0.37271716,  0.61447907, ...,  0.12700564,
         0.21728054,  0.52173803],
       [ 0.32583649,  0.44920006,  0.61447907, ...,  0.12700564,
         0.21728054,  0.52173803],
       ..., 
       [ 0.32583649,  0.44920006,  0.37271716, ...,  0.34629008,
         0.21728054,  0.52173803],
       [ 0.32583649,  0.44920006,  0.37271716, ...,  0.34629008,
         0.12700564,  0.52173803],
       [ 0.32583649,  0.44920006,  0.37271716, ...,  0.34629008,
         0.12700564,  0.21728054]])

In [8]:
plt.hist(resamples, 25, histtype='step');

In [9]:
resamples.shape

(100, 99)

In [10]:
test_statistic = np.mean

In [11]:
meannb = np.mean(resamples)
print meannb

0.481799956265


In [12]:
sb = scipy.stats.skew(resamples)
print sb

[  9.84937059e+00  -6.85714286e+00   5.51037759e+00  -4.69485534e+00
   4.12948321e+00  -3.70546845e+00   3.37060575e+00  -3.09628108e+00
   2.86531189e+00  -2.66666667e+00   2.49289081e+00  -2.33873833e+00
  -2.20039382e+00   2.07500550e+00   1.96039212e+00  -1.85485207e+00
  -1.75703506e+00   1.66585346e+00   1.58041950e+00  -1.50000000e+00
  -1.42398299e+00   1.35185274e+00  -1.28317083e+00  -1.21756156e+00
  -1.15470054e+00   1.09430581e+00   1.03613065e+00  -9.79957887e-01
   9.25595250e-01   8.72871561e-01  -8.21633625e-01  -7.71743633e-01
   7.23076997e-01  -6.75520529e-01   6.28970902e-01  -5.83333333e-01
   5.38520464e-01  -4.94451386e-01   4.51050802e-01   4.08248290e-01
  -3.65977656e-01   3.24176359e-01  -2.82785007e-01   2.41746889e-01
  -2.01007563e-01  -1.60514471e-01   1.20216585e-01  -8.00640769e-02
   4.00080024e-02   7.10980683e-14   4.00080024e-02  -8.00640769e-02
  -1.20216585e-01  -1.60514471e-01   2.01007563e-01   2.41746889e-01
  -2.82785007e-01  -3.24176359e-01

In [13]:
estimate, bias, stderr, conf_interval = jackknife_stats(data, test_statistic, 0.95)

In [14]:
estimate

0.48179995626502442

In [15]:
bias

1.099120794378905e-14

In [16]:
stderr

0.025809392751893444

In [17]:
conf_interval

array([ 0.43121448,  0.53238544])

In [18]:
test_statistic = lambda x: (np.mean(x), np.var(x))

In [19]:
estimate, bias, stderr, conf_interval = jackknife_stats(data, test_statistic, 0.95)

In [20]:
estimate

array([ 0.48179996,  0.06661248])

In [21]:
bias

array([  1.09912079e-14,  -6.66124754e-04])

In [22]:
conf_interval

array([[ 0.43121448,  0.05333065],
       [ 0.53238544,  0.0798943 ]])

In [32]:
def jackknife(data, func):
    """Jackknife estimate of the estimator func"""
    n = len(data)
    idx = np.arange(n)
    return np.sum(func(data[idx!=i]) for i in range(n))/float(n)

In [33]:
def jackknife_var(data, func):
    """Jackknife estiamte of the variance of the estimator func."""
    n = len(data)
    idx = np.arange(n)
    j_est = jackknife(data, func)
    return (n-1)/(n + 0.0) * np.sum((func(data[idx!=i]) - j_est)**2.0
                                    for i in range(n))

In [34]:
# estimate of the variance of an estimator
jackknife_var(data, np.std)

0.00017517566107976549

In [43]:
def calc_avg_leave_one_out_func(func, data):
    means = []
    for i in range(len(data)):
        loo_data = np.hstack([data[:i],data[i+1:]])
        res = func(loo_data)
        means.append(res)
        
        means = np.array(means)
        return means.mean(),means.var()

In [56]:
calc_avg_leave_one_out_func(np.mean,data)

(0.48337534484125655, 0.0)

In [45]:
calc_avg_leave_one_out_func(np.var, data)

(0.06636429050554038, 0.0)

In [89]:
def calculate_bias(data, mean, skew, median):
    jackknife_mean,mean_var = calc_avg_leave_one_out_func(np.mean, data)
    just_mean = np.mean(data)
    
    jackknife_skew,skew_var = calc_avg_leave_one_out_func(st.skew, data)
    just_skew = st.skew(data)
    jackknife_median, median_var = calc_avg_leave_one_out_func(np.median, norm_data)
    just_median = np.median(norm_data)
    
    print ('Just mean Error = {}'.format(abs(just_mean - mean)))
    print ('Jackknife mean Error = {}'.format(abs(jackknife_mean - mean)))
    print ('Jackknife mean Variance = {}'.format(abs(mean_var)))
    
    bias = (n-1)*(jackknife_mean - just_mean)
    print ('Bias = {}\n'.format(bias))

In [90]:
calculate_bias(data, mean, skew, median)

NameError: name 'median' is not defined